[environments.dev]
store = "mkz-shopiflow.myshopify.com"
open = true
ignore = [
  ".git/",
  ".github/",
  ".gitignore",
  ".husky/",
  ".prettierrc.json",
  ".vscode/",
  "commitlint.config.js",
  "node_modules/",
  "package.json",
  "pnpm-lock.yaml",
  "postcss-plugin-no-tw-conflict.js",
  "postcss-plugin-prefix-selector.js",
  "postcss.config.js",
  "shopify.theme.toml",
  "src/**",
]

[environments.pull]
store = "mkz-shopiflow.myshopify.com"
theme = "135571701947"
nodelete = true
ignore = [
  ".git/",
  ".github/",
  ".gitignore",
  ".husky/",
  ".prettierrc.json",
  ".vscode/",
  "assets/app.css",
  "assets/theme-no-conflict.css",
  "assets/app.js",
  "commitlint.config.js",
  "node_modules/",
  "package.json",
  "pnpm-lock.yaml",
  "postcss-plugin-no-tw-conflict.js",
  "postcss-plugin-prefix-selector.js",
  "postcss.config.js",
  "shopify.theme.toml",
  "src/**",
]

[environments.push]
store = "mkz-shopiflow.myshopify.com"
theme = "135571701947"
ignore = [
  ".git/",
  ".github/",
  ".gitignore",
  ".husky/",
  ".prettierrc.json",
  ".vscode/",
  "commitlint.config.js",
  "node_modules/",
  "package.json",
  "pnpm-lock.yaml",
  "postcss-plugin-no-tw-conflict.js",
  "postcss-plugin-prefix-selector.js",
  "postcss.config.js",
  "shopify.theme.toml",
  "src/**",
]